# Generated by Django 5.0.7 on 2024-11-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_student_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
    ]
