# Generated by Django 5.0.7 on 2025-02-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='demo',
            new_name='demo_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files/'),
        ),
    ]
