# Generated by Django 5.0.7 on 2025-02-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_demo_product_demo_url_product_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_imgs/'),
        ),
    ]
