# Generated by Django 5.0.7 on 2025-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_product_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
