# Generated by Django 5.0.7 on 2025-03-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_customer_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='order',
            new_name='customer',
        ),
    ]
